"""The release's assets, checked against each other on every build.

`rewt release-check` already asks these questions well. This file exists so they are
asked whenever anything else is, rather than only when somebody is cutting a release
— *if a step only runs when a person remembers to run it, it is not part of the
build* (AGENTS.md), and a release is exactly the moment nobody wants to discover a
gap.

The class these guard is the one this repository kept meeting: **two artefacts, each
internally consistent, never compared.** The packaged tar against the tiles the
viewer serves, the published attribution against the manifest it is generated from,
the audit against the network published beside it. None of them is findable by a gate
that compares the build with itself, and each was found by someone holding the two
things at once.

The tar was the sharpest instance. `rewt.tiles.pack()` existed and was called by no
code path, so `published/viewer-data.tar` was whatever had last been built by hand
and would have stayed that way through any number of rebuilds — and the release would
have attached it without complaint.
"""

from __future__ import annotations

import pytest

from rewt import paths

pytestmark = pytest.mark.published


@pytest.fixture(scope="module")
def release():
    from rewt import release as module

    if not paths.PUBLISHED.is_dir() or not any(paths.PUBLISHED.iterdir()):
        pytest.skip(
            f"{paths.rel(paths.PUBLISHED)} is empty; the export stage has not run"
        )
    return module


def test_the_packaged_tiles_are_the_tiles_the_viewer_serves(release):
    """Compared by size and digest, never by mtime.

    A clock is a proxy for whether two files agree, and D-049 records what proxies
    have cost here. The instance that makes the argument: `summary.json` was the
    **same size and different bytes** in the tar and on disk, so a size check alone
    would have passed it.
    """
    drift = release.viewer_data_drift()
    assert not drift, (
        "the release would attach tiles that are not the ones the viewer serves:\n  "
        + "\n  ".join(drift)
    )


def test_the_published_attribution_agrees_with_the_manifest(release):
    """*Provenance travels as a pointer.*

    Two renderings of one obligation, generated by different code on different
    schedules from a single manifest. A short attribution may never attribute less
    than `conf/sources.yml` does, and the only way to know it does not is to compare
    them.
    """
    drift = release.attribution_drift()
    assert not drift, (
        "the published attribution and the manifest disagree:\n  "
        + "\n  ".join(drift)
    )


def test_the_audit_is_attached_in_its_own_right(release):
    """*The audit, machine-readable and human-readable, per basin and national* (§7).

    An audit reachable only by unpacking a tar of map tiles is an audit nobody
    checking a claim will open.
    """
    assert release.audit_is_its_own_asset(), (
        "the audit is not attached as its own asset, so a reader has to unpack "
        "something else to reach the evidence for the headline figure"
    )


def test_every_declared_asset_exists(release):
    """A release manifest naming a file that is not there fails at the worst moment."""
    missing = [
        f"{path} ({label})"
        for path, label in release.assets()
        if not path.exists()
    ]
    assert not missing, (
        "the release declares assets that do not exist: " + ", ".join(missing)
    )
